export const buttonStyle = {
    backgroundColor: "#ffffff",
    border: "none",
    color: "#000000",
    padding: "15px 60px",
    textAlign: "center",
    textDecoration: "none",
    display: "flex",
    fontSize: "32px",
    margin: "4px 2px",
    cursor: "pointer",
    borderRadius: "50px",
    borderTop: "1px solid #000000",
    borderBottom: "2.5px solid #000000",
    borderLeft: "1px solid #000000",
    borderRight: "3px solid #000000",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
};